Feat/fid 43/create form
FideCly/dashboard pull request #45
Opened 2022-08-22 18:22 UTC by JeremCy

2022-08-22 20:18 UTC, sihamais requested changes
Points à corriger en + :
- Le titre de la PR est à corriger selon la convention de nommage.
- La description de la PR doit correspondre à la template définie dans les autres repos (tu peux créer le template comme j'ai fais dans les autres repos). Et le numéro du ticket JIRA doit être renseigné dans la description.
- Il y a des messages en anglais et d'autres en français. La plateform doit avoir une seule langue partout. @JeremyLaoo avait dû choisir une langue pour l'app mobile. Le dashboard doit être dans la même langue (le texte visible par les utilisateurs seulement, le code peut rester et doit être en anglais).
- Il faut mettre en place un linter et un formatter. Je vais créer une page notion pour renseigner ça. Tu peux corriger le reste en attendant.
- Pense à mettre en place Dependabot si c'est pas encore fait. Tu peux copier coller la config qu'il y a sur le repo `app`. Tu peux aussi copier le workflow de auto-merge.

2022-08-22 20:18 UTC, sihamais commented on src/Components/form/CardForm.tsx
> +      .post("http://localhost:8080/api/card", formData)
L'url statique du backend doit être stockée dans une variable et concaténée avec la route qu'on veut appeler. Un fichier de config en tsx dans un dossier Config par exemple qui contient ce genre de variable serait idéal

2022-08-22 20:18 UTC, sihamais commented on src/Components/form/EmailForm.tsx
> +      .post("http://localhost:8080/api/email", formData)
Pareil pour l'url

2022-08-22 20:18 UTC, sihamais commented on src/Components/form/ProfileForm.tsx
> +      .post("http://localhost:8080/api/profile", formData)
Pareil pour l'url

2022-08-22 20:18 UTC, sihamais commented on src/Components/form/ProfileForm.tsx
> +    formData.append("website", data.website);
Fais attention les champs que t'utilise ici pour former ton formData ne correspondent pas tous aux champs postman qu'on a défini

2022-08-22 20:18 UTC, sihamais commented on src/Components/form/PromotionForm.tsx
> +      .post("http://localhost:8080/api/promotion", formData)
Pareil pour l'url. Un truc du genre `.post(ServerUrl + "/promotion")`

2022-08-22 20:18 UTC, sihamais commented on src/Components/form/PromotionForm.tsx
> +        </div> */}
Faut éviter de garder des bouts de code commentés. Si c'est pas utilisé faut les enlever pour garder le code propre

2022-08-22 20:18 UTC, sihamais commented on src/Views/App.tsx
> +const WSS_FEED_URL = "ws://localhost:8080/ws";
C'est déja mieux pour l'url ici mais encore mieux si c'est dans un fichier de config à part

2022-08-22 20:18 UTC, sihamais commented on src/Views/Client/Scanner.tsx
> +          if (!!result) {
Pourquoi pas juste `if(result)` ?

2022-08-22 20:18 UTC, sihamais commented on src/Views/Client/Scanner.tsx
> +          if (!!error) {
Pourquoi pas `if(error)` ?

2022-08-23 10:57 UTC, sihamais requested changes
Il y a des trucs à corriger encore, regarde les commentaires de ma derniere review

2022-10-17 15:04 UTC, sihamais requested changes
J'ai fais des suggestion autant que je le pouvais pour te faciliter les corrections.
Pense à renommer la PR suivant les conventions de nommage.
Tu devra probablement corriger les payloads quand la PR de l'api sera mergée.
Dans l'ensemble c'est bon. Cette PR devrait être mergée assez vite. Pense àa résoudre les conflits au plus vite pour vérifier que les checks passent.
Hésite pas à marquer `Done` sur les commentaires qui ont déja été traités pour que je sache plus facilement ce qui a été fait.

2022-10-17 18:28 UTC, JeremCy commented on src/Components/form/CardForm.tsx
> +              <div className="mt-2 alert alert-danger">endAt is required</div>
done

2022-10-17 18:28 UTC, JeremCy commented on src/Components/form/CardForm.tsx
> +              <div className="mt-2 alert alert-danger">startAt is required</div>
done

2022-10-17 18:28 UTC, JeremCy commented on src/Components/form/CardForm.tsx
> +            <label htmlFor="startAt">startAt</label>
done

2022-10-17 18:28 UTC, JeremCy commented on src/Components/form/CardForm.tsx
> +            <label htmlFor="endAt">endAt</label>
done

2022-10-17 18:29 UTC, JeremCy commented on src/Components/form/PromotionForm.tsx
> +              placeholder="Enter limitPassage"
done

2022-10-17 18:29 UTC, JeremCy commented on src/Components/form/PromotionForm.tsx
> +            <label htmlFor="limitAmout">limitAmout</label>
done

2022-10-17 18:30 UTC, JeremCy commented on src/Components/form/PromotionForm.tsx
> +            <label htmlFor="valimitPassagelue">limitPassage</label>
done

2022-10-17 18:31 UTC, JeremCy commented on src/Components/form/PromotionForm.tsx
> +            <label htmlFor="endAt">endAt</label>
done

2022-10-17 18:31 UTC, JeremCy commented on src/Components/form/PromotionForm.tsx
> +            <label htmlFor="type">type</label>
done

2022-10-17 18:32 UTC, JeremCy commented on src/Components/form/PromotionForm.tsx
> +              placeholder="Enter limitAmout"
done

2022-10-17 18:33 UTC, JeremCy commented on src/Components/form/PromotionForm.tsx
> +            <label htmlFor="startAt">startAt</label>
done

2022-10-17 18:33 UTC, JeremCy commented on src/Components/form/ShopForm.tsx
> +                placeholder="Enter phone"
done

2022-10-17 18:33 UTC, JeremCy commented on src/Components/form/ShopForm.tsx
> +              <label htmlFor="phone">phone</label>
done

2022-10-17 18:34 UTC, JeremCy commented on src/Components/form/ShopForm.tsx
> +                placeholder="Enter geoloc"
done

2022-10-17 18:34 UTC, JeremCy commented on src/Components/form/ShopForm.tsx
> +              <label htmlFor="geoloc">geoloc</label>
done

2022-10-17 18:34 UTC, JeremCy commented on src/Components/form/ShopForm.tsx
> +                placeholder="Enter zipCode"
done

2022-10-17 18:34 UTC, JeremCy commented on src/Components/form/ShopForm.tsx
> +              <label htmlFor="zipCode">zipCode</label>
done

2022-10-17 18:35 UTC, JeremCy commented on src/Components/form/ShopForm.tsx
> +              <label htmlFor="email">email</label>
done

2022-10-17 18:35 UTC, JeremCy commented on src/Components/form/ShopForm.tsx
> +            <label htmlFor="siret">siret</label>
done

2022-10-17 18:35 UTC, JeremCy commented on src/Components/form/ShopForm.tsx
> +              placeholder="Enter siret"
done

2022-10-17 18:35 UTC, JeremCy commented on src/Components/form/ShopForm.tsx
> +              placeholder="Enter siren"
done

2022-10-17 18:36 UTC, JeremCy commented on src/Components/form/ShopForm.tsx
> +            <label htmlFor="siren">siren</label>
done

2022-10-17 18:37 UTC, JeremCy commented on src/Components/form/SignupForm.tsx
> +            )}
done

2022-10-17 18:37 UTC, JeremCy commented on src/Components/form/SignupForm.tsx
> +            <label htmlFor="username">username</label>
done

2022-10-17 18:39 UTC, JeremCy commented on src/Views/App.tsx
> +const WSS_FEED_URL = "ws://localhost:8080/ws";
done

2022-10-17 18:40 UTC, JeremCy commented on src/Views/Client/Mailing.tsx
> +          Create Campagne
done

2022-10-17 18:41 UTC, JeremCy commented on src/Views/Settings/GeneralSettings.tsx
> +        <h1 className="flex-1 text-4xl">GeneralSettings</h1>
done

2022-10-18 12:48 UTC, JeremCy commented on src/Components/form/ProfileForm.tsx
> +    formData.append("website", data.website);
done

2022-10-18 12:48 UTC, JeremCy commented on src/Components/form/EmailForm.tsx
> +      .post("http://localhost:8080/api/email", formData)
done

2022-10-18 12:49 UTC, JeremCy commented on src/Components/form/CardForm.tsx
> +      .post("http://localhost:8080/api/card", formData)
done

2022-10-18 12:49 UTC, JeremCy commented on src/Views/Client/Scanner.tsx
> +          if (!!result) {
done

2022-10-18 12:49 UTC, JeremCy commented on .env
> +REACT_APP_WEBSOCKET_URL = "ws://localhost:3001/"
done

2022-12-06 20:04 UTC, sihamais requested changes
Pas grand chose à corriger. Il reste quelques checks de la CI qui passent pas

2022-12-08 09:15 UTC, sihamais approved these changes

2022-12-08 09:16 UTC, merged