Feat/fid 43/create api module
FideCly/dashboard pull request #534
Opened 2023-01-25 15:57 UTC by JeremCy

### Changes
- a creation of an API layer for stopping the use of multiple Axios on a single page.
- all the new changes concerning the API are in the API folder
- there are two forms and lists that are now up to date for working with this layer
[FID-43]

2023-01-26 16:41 UTC, sihamais requested changes

2023-01-26 16:41 UTC, sihamais commented on src/Api/Models/Campaign.ts
> +export default interface Campaign {
Campaign correspond à quel objet dans le back ?

2023-01-26 16:41 UTC, sihamais commented on src/Api/Models/Profile.ts
> +export default interface Profile {
Profile correspond a quel objet dans le back ? Si c'est pas implémenté dans le back vaut mieux l'enlever et on pourra rajouter ce qu'on veut par la suite

2023-01-26 16:41 UTC, sihamais commented on src/Api/Models/Shop.ts
> +  geoloc: string
J'ai séparé la géoloc en deux champs `lat` et `long`

2023-01-26 16:41 UTC, sihamais commented on src/Api/Services/CardService.ts
> +  return await http.get<Card[]>('/cards')
Si tu veux optimiser tu peux créer une variable avec le chemin "/cards" dedans. C'est juste une suggestion t'es pas obligé de le faire

2023-01-26 16:41 UTC, sihamais commented on src/Api/Services/ProfileServices.ts
> +  return await http.get<Profile[]>('/profiles')
La route `/profiles` existe pas pour l'instant. Si c'est nécessaire pour le dashboard on peut en discuter pendant l'hebdo ou tu peux créer une user story si yen a pas dans les sprints futurs

2023-01-26 16:41 UTC, sihamais commented on src/Components/List/CampagneList.tsx
> +        const response = await PromotionService.getPromotions()
Il faudrait plutot fetch les promotions du shop actuel. Il ya une nouvelle méthode dans le back qui permet de récupérer ça https://github.com/FideCly/api#get-a-shops-promotions

2023-01-26 16:41 UTC, sihamais commented on src/Components/List/CardList.tsx
> +        const response = await CardService.getCards()
Est-ce que tu fetch toutes les cartes ? Même celles des autres shops ? Si besoin tu peux créer un ticket pour que je rajoute une route qui permet de fetch les cards d'un shop. Et en même temps crée toi un ticket pour que tu mette a jour le endpoint utilisé ici. Pour l'instant je te bloquerai pas le merge pour ça

2023-01-26 16:41 UTC, sihamais commented on src/Components/List/PromotionList.tsx
> +        const response = await PromotionService.getPromotions()
Pareil que pour campaign, d'ailleurs c'est quoi campaign. Il me semble qu'on a pas cette feature dans le back

2023-01-26 16:41 UTC, sihamais commented on src/Components/List/ShopList.tsx
> +        const response = await ShopService.getShops()
Enfait on a décidé que pour l'instant il n'y aurait qu'un seul shop par enseigne, donc cette méthode devrait fetch le shop actuel. (Malheureusement on a pas encore lié les shops à des users pour représenter les employés donc ça viendra par la suite). Fais toi un ticket pour t'en rappeler, Je te bloquerai pas le merge pour ça

2023-01-26 16:41 UTC, sihamais commented on src/Components/form/ShopForm.tsx
> +    geoloc: ''
géoloc en deux champs maintenant

2023-01-26 16:41 UTC, sihamais commented on src/Components/form/ShopForm.tsx
> +      geoloc: shop.geoloc
Géoloc en deux champs

2023-01-26 16:41 UTC, sihamais commented on src/Components/form/ShopForm.tsx
> +          geoloc: response.data.geoloc
géoloc en deux champs

2023-01-26 16:41 UTC, sihamais commented on src/Components/form/ShopForm.tsx
> +        </div>
Géoloc en deux champs

2023-01-26 16:41 UTC, sihamais commented on src/Views/Client/Mailing.tsx
>          <h1 className="flex-1 text-4xl">Mailing</h1>
Ah je vois donc campaign c'est lié au mailing. Tu peux déja rajouter un ticket dans la user story qui parle de ça pour que ça soit implémenté dans le back

2023-01-27 13:35 UTC, JeremCy commented on src/Api/Models/Campaign.ts
> +export default interface Campaign {
l'object n'at pas encore ete cree en back c'est les campagne marketing via email

2023-02-06 11:29 UTC, JeremCy commented on src/Components/form/ShopForm.tsx
> +    geoloc: ''
done

2023-02-06 11:29 UTC, JeremCy commented on src/Components/form/ShopForm.tsx
> +      geoloc: shop.geoloc
done

2023-02-06 11:30 UTC, JeremCy commented on src/Components/form/ShopForm.tsx
> +          geoloc: response.data.geoloc
done

2023-02-06 11:30 UTC, JeremCy commented on src/Components/form/ShopForm.tsx
> +        </div>
done

2023-02-06 11:30 UTC, JeremCy commented on src/Views/Client/Mailing.tsx
>          <h1 className="flex-1 text-4xl">Mailing</h1>
je l'ai supprimer et je remettrais plus tard

2023-02-06 11:31 UTC, JeremCy commented on src/Api/Models/Shop.ts
> +  geoloc: string
done

2023-02-06 11:31 UTC, JeremCy commented on src/Api/Models/Profile.ts
> +export default interface Profile {
cela a ete suprime

2023-02-06 11:31 UTC, JeremCy commented on src/Api/Models/Campaign.ts
> +export default interface Campaign {
cela a ete suprimer

2023-02-17 09:38 UTC, closed without merging